### ISSUE TITLE
004: Agile

### ISSUE THREAD

**Issue by kubek2k** [peel/podcast#18]

**Comment by kwasniew** [comment]
* agile manifest and it's methods are older than some interns, world has moved on
* agile development != scrum , methods fixation
* agile coach (why coaching is mostly about rituals?)
* certification (https://dannorth.net/2016/07/04/how-to-train-your-agile/)
* flaccid scrum (https://martinfowler.com/bliki/FlaccidScrum.html)
* agile meetups: too much lego, not enough hard skills
* dirt under your nails - stay technical, don't be woo woo agilist
* does Silicon Valley care: https://www.quora.com/Do-professional-coding-teams-in-Silicon-Valley-e-g-Google-Airbnb-also-use-Scrum-Or-do-they-use-a-more-efficient-way-to-organize-each-other
* do FB devs care? https://twitter.com/dan_abramov/status/945073584753594368?lang=en
* this is not real scrum man!
* get off your training wheels
* study deeper: psychology of people and interactions

**Comment by kwasniew** [comment]
* Minęło 17 lat od powstania manifestu Agile Software Development.
Co poszło nie tak w nieudanych zwinnych instalacjach? Co ogranicza nas przed dalszym postępem?
Jakie są Twoje pet peeves związane z samym manifestem i jego konkretnymi implementacjami?

* W jakie praktyki warto zainwestować jako alternatywę do tych które są bezkrytycznie stosowane niczym rytuały plemienne?
Które praktyki są ok i powinny być bardziej eksponowane?

* TL;DL 1 minutowe call to action dla słuchaczy
