### ISSUE TITLE
003: Object-orientation

### ISSUE THREAD

**Issue by kubek2k** [peel/podcast#19]
Agenda:
  - Jak rozumiecie OO, definicja kontra praktyka
  - OO w przyrodzie - Java/C++ kontra reszta swiata
  - Największe plusy i minusy OO 
  - Gdybyś miał rozpoczynac nowy projekt to czy wybralbys jezyk OO. Dlaczego tak/nie?

**Comment by kwasniew** [comment]
* why we have paradigms? (Programming across paradigms - https://www.youtube.com/watch?v=Pg3UeB-5FdA)
* OO without classes. Why I don't like JS classes (https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch6.md)
* composability problem (https://www.youtube.com/watch?v=SfWR3dKnFIo - Oh Composable World!)

**Comment by kubek2k** [comment]
Alan Kay on OO: http://wiki.c2.com/?AlanKaysDefinitionOfObjectOriented i https://softwareengineering.stackexchange.com/questions/46592/so-what-did-alan-kay-really-mean-by-the-term-object-oriented

**Comment by kwasniew** [comment]
2 edycja klasycznej pozycji w JS i z mniejszą ilością klas: https://martinfowler.com/articles/201803-refactoring-2nd-ed.html

**Comment by peel** [comment]
- Object-Oriented Programming Versus Abstract Data Types, Cook, William R., 1990 http://www.cs.utexas.edu/users/wcook/papers/OOPvsADT/CookOOPvsADT90.pdf
-  On understanding data abstraction, revisited., Cook, William R., 2009 http://www.cs.utexas.edu/~wcook/Drafts/2009/essay.pdf
- Unfolding Abstract Data Types, Gibbons, Jeremy, 2008 http://www.comlab.ox.ac.uk/jeremy.gibbons/publications/adt.pdf
- DSL discussions, 2012 http://lambda-the-ultimate.org/node/4560

**Comment by Machcak** [comment]
Cześć, 
jeszcze nie przesłuchałem do końca tego odcinka ale już jestem zadowolony, że trafiłem na Was podcast. Od kilku lat programuje "obiektowo" i tak właśnie podskórnie czułem, że coś jest nie tak albo ze mną albo z Javą :) Otwieracie oczy, dziękuję.
