### ISSUE TITLE
001: fixation

### ISSUE THREAD

**Issue by peel** [peel/podcast#5]
## Shownotes
[2017-10-29-001-zajawki.md](https://github.com/peel/podcast/blob/master/_posts/2017-10-29-001-zajawki.md)

**Comment by kwasniew** [comment]
Komentarz, który dostałem mailem: w jaki sposób podchodzicie do nowego tematu. Tematu, o którym nie macie pojęcia lub wasza wiedza jest bardzo ograniczona. Jestem ciekaw jak to zrobić dobrze, gdzie szukać tematów - zakładając, że nie masz znajomego który może coś o tym wiedzieć.

**Comment by peel** [comment]
Umknelo mi. Ja zasadniczo nie siegam po rzeczy w ktorych nie mam w ogole o co sie zaczepic. Zazwyczaj jest tak, ze albo jakas wiedza jest przenaszalna albo mam jakis kat z jakiego moge ogarnac progresywne wejscie w zagadnienie. Z tym, ze jesli juz po cos siegam to dlatego, ze rozwiazuje jakis moj problem. Dzieki czemu mam od razu usecase i proboje dany temat zaaplikowac. Chociaz czasem nie wychodzi.

**Comment by kubek2k** [comment]
feedback od kolegi:
  * u mnie:
    * problem z przesterami na literach c i z
    * yyyy uuuu eeee
  * pro montaz i jakosc dzwieku (nawet nie zauwazyl ze mateusz nadawal z piwnicy)
  * mial zastrzerzenia do tego ze przekazujemy sobie glos (mam wrazenie ze chodzilo o brak osoby prowadzacej odcinek)
  * kontent pro
